### ISSUE TITLE
Ctrl-C doesn't close the message-tool.

### ISSUE THREAD

**Issue by nimrodshn** [container-mgmt/messaging-library#72] opened 2018-07-04 09:38 UTC
Pressing Ctrl-C doesn't close the message-server.

cc: @yaacov @zgalor

**Comment by yaacov** [comment] 2018-07-04 10:28
I'm assigning this to you since you can reproduce and solve it.

**Comment by nimrodshn** [comment] 2018-07-04 10:35
@yaacov @zgalor also reproduced this.. if you don't want to handle it that's fine i'll close it.

**Comment by yaacov** [comment] 2018-07-04 10:39
> @zgalor also reproduced this.. if you don't want to handle it that's fine i'll close it.

@nimrodshn  I want you ( with @zgalor help, if he can also reproduce ) to handle it.

I can not handle it because ctrl-c breaks the server on my machines ( home and work )

```
~/go/src/github.com/container-mgmt/messaging-library$ .gopath/bin/messaging-server serve 
I0704 13:34:05.036245   20502 serve.go:71] Your friendly STOMP broker (YFSB) server 127.0.0.1:61613: [listen to all]
^C
~/go/src/github.com/container-mgmt/messaging-library$
```

**Comment by nimrodshn** [comment] 2018-07-04 10:53
@yaacov Please check if Ctrl-C works on `messaging-tool`?
I got confused between messaging-tool and messaging-server.

**Comment by yaacov** [comment] 2018-07-04 10:54
Ahh, we know that ... you can fix it if you want ...

**Comment by nimrodshn** [comment] 2018-07-04 10:54
Working on it with @zgalor  :+1:

**Comment by yaacov** [comment] 2018-07-04 12:23
closed by #73

**Closed by yaacov** 2018-07-04 12:23 UTC
Labels: question
